//
// Created by rfish on 6/11/2024.
//

#ifndef KOI_NETWORK_ENUMS_HPP
#define KOI_NETWORK_ENUMS_HPP

namespace Koi { namespace Network {

enum Error : int {
    SOCKET_PEER_ERROR_OK = 0,
    SOCKET_PEER_ERROR_PROTOCOL,
    SOCKET_PEER_ERROR_INVALID_SOCKET,
    SOCKET_PEER_ERROR_SIZE,
};

enum Mode : int {
    SOCKET_PEER_MODE_INVALID = -1,
    SOCKET_PEER_MODE_MIN = 0,
    SOCKET_PEER_MODE_CLIENT = SOCKET_PEER_MODE_MIN,
    SOCKET_PEER_MODE_SERVER,
    SOCKET_PEER_MODE_SIZE
};


enum Protocol : int {
    SOCKET_PEER_PROTOCOL_INVALID = -1,
    SOCKET_PEER_PROTOCOL_MIN = 0,
    SOCKET_PEER_PROTOCOL_STREAM = SOCKET_PEER_PROTOCOL_MIN,
    SOCKET_PEER_PROTOCOL_DATAGRAM,
    SOCKET_PEER_PROTOCOL_SIZE
};

}
}

#endif //KOI_NETWORK_ENUMS_HPP
